# This is a basic workflow to help you get started with Actions

name: Build Windows Release

# Controls when the workflow will run
on:
  workflow_dispatch:

env:
  PROJ_URL: "https://drive.google.com/file/d/1Bs4F3Yrag_oiQ8Pn-JulG-uqdwk8wMtY/view?usp=sharing"
  PROJ_ROOT: "./inst_proj_9.5.1_vs2022"
  SQLITE_URL: "https://drive.google.com/file/d/1ieOMSBXV694Yq8alACFGX5mwdqCPxZsW/view?usp=sharing"
  SQLITE_ROOT: "./inst_sqlite_3.47.2"

permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        shell: cmake -P {0}
        run: |
          file(DOWNLOAD "$ENV{PROJ_URL}" ./proj.zip SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./proj.zip)
          file(DOWNLOAD "$ENV{SQLITE_URL}" ./sqlite.zip SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./sqlite.zip)
      - name: Configure
        shell: bash
        run: |
          mkdir build
          mkdir instdir
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -A x64 \
                -DPROJ_ROOT:PATH=$ENV{PROJ_ROOT} \
                -DSQLite3_ROOT:PATH=$ENV{SQLITE_ROOT} \
                -DCMAKE_INSTALL_PREFIX:PATH=instdir
      - name: Build
        shell: bash
        run: cmake --build build --config Release
      - name: Make archive
        shell: bash
        run: 7z a -tzip wmdepends_win64.zip
      - name: Upload 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: gh release create v1.0 wmdepends_win64.zip
